### ISSUE TITLE
AngularGM no longer works with Oct. 11, 2015 update to 3.22 release of Google Maps API

### ISSUE THREAD

**Issue by jdkenney** [dylanfprice/angular-gm#83] opened 2015-10-13 18:23 UTC
As in title:

AngularGM <gm-map> directive no longer works with the 3.22 (exp) update as of Oct. 11, 2015. The AngularGM demo page is also currently broken: http://dylanfprice.github.io/angular-gm/1.0.2/examples/#!/map/

Unfortunately the release notes (https://developers.google.com/maps/documentation/javascript/releases#322) for exp are only current to Sept. 22, 2015 so I'm not sure what changed in this update.

The problem is at least with changing the value of center in the gm-center attribute, although it seems like the initial location specified in gm-map-options is also ignored.

**Comment by frankcrisa** [comment] 2015-11-04 10:49
I see this issue too.
Probably this issue is generated by the fact that since version 3.22 the pan control of the map is no longer available. 
At the moment, the solution is to explicitly call version 3.21, that is the current "release" version. This version will change to "frozen" in November 2015 but it will removed on February 2016.

**Comment by frankcrisa** [comment] 2015-11-04 13:15
I found the solution, the problem is with the object LatLng. With version 3.22 it was changed its structure and $scope.center = new google.maps.LatLng (lat, lng) is no longer executed.
It must be replaced with  $scope.gmap.panTo(new google.maps.LatLng(lat, lng))
This is my simple_map.js for the demo at: http://dylanfprice.github.io/angular-gm/1.0.2/examples/#!/map/

angular.module('simple-map', ['AngularGM'])
.run(function (angulargmContainer, $rootScope) {
                var gmapPromise = angulargmContainer.getMapPromise('simpleMap');
                gmapPromise.then(function (gmap) {
                    // google map configuration here
                    $rootScope.gmap = gmap;
                });
            })
.controller('SimpleMapCtrl', function($scope) {
  $scope.$watch('center', function(center) {
   if (center) {
     $scope.centerLat = center.lat();
     $scope.centerLng = center.lng();
   }
  });
  
  $scope.updateCenter = function(lat, lng) {
   // $scope.center = new google.maps.LatLng(lat, lng);
       $scope.gmap.panTo(new google.maps.LatLng(lat, lng));
  };
});

**Comment by dylanfprice** [comment] 2015-11-04 15:39
Great thanks @frankcrisa I will try to get a fix out this weekend.

**Comment by janhoffmann** [comment] 2015-11-05 13:56
@frankcrisa works for me, thanks!

**Comment by dylanfprice** [comment] 2015-11-08 21:12
I pushed a fix for this, which involved changing the contract of gm-center to deal in google.maps.LatLngLiteral objects instead of google.maps.LatLng objects. I'll go through the process of putting out a new version when I get another chance.

**Closed** 2017-01-04 22:11 UTC
